api_platform:
    title: Sortir.com API
    version: 1.0.0
    formats:
        json: ["application/json"]
    docs_formats:
        json: ["application/json"]
        html: ["text/html"]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
