twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        profilePicturesDirectory: '%app.profilePicturesDirectory%'

when@test:
    twig:
        strict_variables: true
